services:
  - type: web
    name: analyse-cloture
    env: python
    buildCommand: ""
    startCommand: "gunicorn main:app"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: 8415756245:AAHaU2KBRsC3q05eLld2JjMt_V7S9j-o4ys
      - key: CHAT_ID
        sync: 5814604646