services:
  - type: web
    name: analyse-cloture
    env: python
    buildCommand: ""
    startCommand: "gunicorn main:app"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false